[package]
name = "miceless"
version = "0.1.0"
description = "Control your mouse with your keyboard"
authors = [ "Sandorex" ]
repository = "https://github.com/sandorex/miceless"
license = "GPL-2.0-or-later"
edition = "2024"
readme = "README.md"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive", "env"] }
serde = { version = "1.0.228", features = ["derive"] }
evdev = { version = "0.13.2" }
# sdl3 = { version = "0.18.4", features = ["build-from-source-static", "ttf"] }
sdl3 = { version = "0.18.4", features = ["use-pkg-config", "ttf"] }

[features]
static = ["sdl3/static-link"]
