[package]
name = "miceless"
version = "0.1.0"
description = "Control your mouse with your keyboard"
authors = [ "Sandorex" ]
repository = "https://github.com/sandorex/miceless"
license = "GPL-2.0-or-later"
edition = "2024"
readme = "README.md"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive", "env"] }
serde = { version = "1.0.228", features = ["derive"] }
sdl3 = { version = "0.18.4", features = ["use-pkg-config", "ttf"] }
env_logger = "0.11.11"

evdev = { version = "0.13.2", optional = true }
evdev-rs = { version = "0.6.3", optional = true }
toml = "1.1.4"

[features]
default = ["evdev-rust"]
static = ["sdl3/static-link"]
evdev-native = ["dep:evdev-rs"]
evdev-rust = ["dep:evdev"]
